<a href="https://colab.research.google.com/github/evjeeenji/Serial_killers/blob/main/serials_killers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files


uploaded = files.upload() # dictionary, який Colab створює автоматично коли завантажуєш файли через files.upload()

Saving 5_to_14_victim_count.csv to 5_to_14_victim_count.csv
Saving 15_to_30_victim_count.csv to 15_to_30_victim_count.csv
Saving Highest_victim_count.csv to Highest_victim_count.csv
Saving Lessthan_5_victim_count.csv to Lessthan_5_victim_count.csv

In [3]:
import pandas as pd
import numpy as np

dfs = list(uploaded.keys()) # отримуємо список імен завантажених файлів
df1 = pd.read_csv(dfs[0]) # читаємо перший файл,
df2 = pd.read_csv(dfs[1]) # другий файл
df3 = pd.read_csv(dfs[2]) # третій файл
df4 = pd.read_csv(dfs[3]) # четвертий файл

In [4]:
print(df1.shape) # перевіряємо обсяг кожного файла
print(df2.shape)
print(df3.shape)
print(df4.shape)

(164, 6)
(78, 6)
(34, 6)
(29, 6)

In [5]:
# Об'єднуємо таблиці
combined = pd.concat([df1, df2, df3, df4], ignore_index=True, sort=False)

# Перевіряємо розмір
print('Rows:', combined.shape[0], 'Columns:', combined.shape[1])

Rows: 305 Columns: 6

In [6]:
# Прибираємо дублікати
combined = combined.drop_duplicates()

# Перевірка
print("Rows:", combined.shape[0], "Columns:", combined.shape[1])
display(combined.head())

Rows: 305 Columns: 6

,Name,Country,Years active,Proven victims,Possible victims,Notes
0,Carl Eugene Watts,United States,1974 to 1982,14,80+,Believed to have killed over 80 women in multi...
1,Philipp Tyurin,Soviet Union,1945 to 1946,14,29,"Known as the ""Leningrad Maniac"" and the ""Hellr..."
2,Zdzisław Marchwicki,Poland,1964 to 1970,14,21+,Also known as Vampire of Zagłębie. Killed 14 w...
3,Monster of Florence,Italy,1968 to 1985,14,16,Unidentified killer who shot couples in lovers...
4,Joachim Kroll,West Germany,1955 to 1976,14,NaN,"Known as the ""Ruhr Cannibal"" and ""The Duisburg..."

In [7]:
# Зберігаємо об'єднаний файл, щоб вручну додати дати народжень в Google Sheets
from google.colab import files

combined.to_csv("combined.csv", index=False)
files.download("combined.csv")

In [8]:
# Завантажуємо файл вже з датами народжень
from google.colab import files


serial_killers_birth = files.upload()

Saving Serial_killers_data.xlsx to Serial_killers_data.xlsx

In [9]:
sk = pd.read_excel(list(serial_killers_birth.keys())[0])
display(sk.head())

,Name,Country,Years active,Proven victims,Possible victims,Notes,birth_date,birth_day,birth_month,birth_year
0,Carl Eugene Watts,United States,1974 to 1982,14,80+,Believed to have killed over 80 women in multi...,1953-11-07 00:00:00,7.0,11.0,1953.0
1,Philipp Tyurin,Soviet Union,1945 to 1946,14,29,"Known as the ""Leningrad Maniac"" and the ""Hellr...",1910,NaN,NaN,1910.0
2,Zdzisław Marchwicki,Poland,1964 to 1970,14,21+,Also known as Vampire of Zagłębie. Killed 14 w...,1927-10-18 00:00:00,18.0,10.0,1927.0
3,Monster of Florence,Italy,1968 to 1985,14,16,Unidentified killer who shot couples in lovers...,NaN,NaN,NaN,NaN
4,Joachim Kroll,West Germany,1955 to 1976,14,NaN,"Known as the ""Ruhr Cannibal"" and ""The Duisburg...",1933-04-17 00:00:00,17.0,4.0,1933.0

In [10]:
# birth_date читається як datetime з часом, а birth_day, birth_month, birth_year як float з .0

# Прибираємо час з дати
sk['birth_date'] = pd.to_datetime(sk['birth_date'], errors='coerce').dt.date

# Прибираємо .0 з числових колонок
sk['birth_day'] = sk['birth_day'].astype('Int64')
sk['birth_month'] = sk['birth_month'].astype('Int64')
sk['birth_year'] = sk['birth_year'].astype('Int64')

display(sk.head(10))

,Name,Country,Years active,Proven victims,Possible victims,Notes,birth_date,birth_day,birth_month,birth_year
0,Carl Eugene Watts,United States,1974 to 1982,14,80+,Believed to have killed over 80 women in multi...,1953-11-07,7,11,1953
1,Philipp Tyurin,Soviet Union,1945 to 1946,14,29,"Known as the ""Leningrad Maniac"" and the ""Hellr...",1970-01-01,<NA>,<NA>,1910
2,Zdzisław Marchwicki,Poland,1964 to 1970,14,21+,Also known as Vampire of Zagłębie. Killed 14 w...,1927-10-18,18,10,1927
3,Monster of Florence,Italy,1968 to 1985,14,16,Unidentified killer who shot couples in lovers...,NaT,<NA>,<NA>,<NA>
4,Joachim Kroll,West Germany,1955 to 1976,14,NaN,"Known as the ""Ruhr Cannibal"" and ""The Duisburg...",1933-04-17,17,4,1933
5,Arthur Shawcross,United States,1972 to 1989,14,NaN,"Committed arson and burglary, served two years...",1945-06-06,6,6,1945
6,The Doodler,United States,1974 to 1975,14,NaN,Unidentified serial killer who sketched then s...,NaT,<NA>,<NA>,<NA>
7,Marcelo Costa de Andrade,Brazil,1991,14,NaN,Known as The Vampire of Niterói. Raped and kil...,1967-01-02,2,1,1967
8,Julio Pérez Silva,Chile,1998 to 2001,14,NaN,Known as The Psychopath from Alto Hospicio; ki...,1963-07-15,15,7,1963
9,Sergey Shipilov,Russia,1995 to 1999,14,NaN,"Known as the ""Velsk Chikatilo""; killed female ...",1959-05-17,17,5,1959

In [11]:
# Визначаємо знак зодіаку для кожного вбивці на основі дня і місяця народження.Якщо хоча б одне зі значень відсутнє - повертаємо None
def get_zodiac(day, month):
    if pd.isna(day) or pd.isna(month):
        return None
    day = int(day)
    month = int(month)

    if (month == 1 and day < 20) or (month == 12 and day >= 22):
        return "Capricorn"
    elif (month == 1 and day >= 20) or (month == 2 and day < 19):
        return "Aquarius"
    elif (month == 2 and day >= 19) or (month == 3 and day < 21):
        return "Pisces"
    elif (month == 3 and day >= 21) or (month == 4 and day < 20):
        return "Aries"
    elif (month == 4 and day >= 20) or (month == 5 and day < 21):
        return "Taurus"
    elif (month == 5 and day >= 21) or (month == 6 and day < 21):
        return "Gemini"
    elif (month == 6 and day >= 21) or (month == 7 and day < 23):
        return "Cancer"
    elif (month == 7 and day >= 23) or (month == 8 and day < 23):
        return "Leo"
    elif (month == 8 and day >= 23) or (month == 9 and day < 23):
        return "Virgo"
    elif (month == 9 and day >= 23) or (month == 10 and day < 23):
        return "Libra"
    elif (month == 10 and day >= 23) or (month == 11 and day < 22):
        return "Scorpio"
    elif (month == 11 and day >= 22) or (month == 12 and day < 22):
        return "Sagittarius"

sk['zodiac'] = sk.apply(lambda row: get_zodiac(row['birth_day'], row['birth_month']), axis=1)

# Перевірка
print(sk[['Name', 'birth_day', 'birth_month', 'zodiac']].dropna(subset=['zodiac']))

                         Name  birth_day  birth_month       zodiac
0           Carl Eugene Watts          7           11      Scorpio
2         Zdzisław Marchwicki         18           10        Libra
4               Joachim Kroll         17            4        Aries
5            Arthur Shawcross          6            6       Gemini
7    Marcelo Costa de Andrade          2            1    Capricorn
..                        ...        ...          ...          ...
299            Patrick Mackay         25            9        Libra
300       Leonarda Cianciulli         14            4        Aries
302               Albert Fish         19            5       Taurus
303            Heriberto Seda         31            7          Leo
304               John Martin          9           12  Sagittarius

[220 rows x 4 columns]

In [12]:
# Розподіл по знакам
print(sk['zodiac'].value_counts())

zodiac
Pisces         26
Scorpio        23
Sagittarius    23
Aquarius       21
Capricorn      21
Aries          19
Cancer         17
Gemini         16
Taurus         16
Libra          15
Leo            13
Virgo          10
Name: count, dtype: int64

In [13]:
# Цікавить чи цей розподіл є випадковим. Можемо сформувати гіпотези.
# H₀ (нульова): розподіл знаків зодіаку серед серійних вбивць є випадковим (усі знаки мають однакову ймовірність).
# H₁ (альтернативна): розподіл не є випадковим (деякі знаки, наприклад Риби, зустрічаються значно частіше).

from scipy.stats import chisquare

# Дані
observed = np.array([26,23,23,21,21,19,17,16,16,15,13,10])
expected = np.array([observed.sum()/12]*12)

# χ²-тест
chi_stat, p_value = chisquare(observed, expected)

print("Chi-square:", chi_stat)
print("p-value:", p_value)

# Висновок залежно від p-value
alpha = 0.05
if p_value > alpha:
    print("Не відхиляємо нульову гіпотезу.")
else:
    print("Відхиляємо нульову гіпотезу.")

Chi-square: 13.01818181818182
p-value: 0.29213871575843114
Не відхиляємо нульову гіпотезу.

In [14]:
# Щоб побудувати дашборд Tableau "Кількість маніяків по країні", потрібно стандартизувати поле з країнами.
# У датасеті є:
# 1) неіснуючі країни (наприклад, СРСР)
# 2) записи з кількома країнами в одному полі
# Ці значення потрібно очистити та привести до сучасних назв країн, щоб карта та агрегація працювали правильно.

print(sk['Country'].unique())

['United States' 'Soviet Union' 'Poland' 'Italy' 'West Germany' 'Brazil'
 'Chile' 'Russia' 'South Korea' 'Pakistan' 'Latvia' 'South Africa'
 'United Kingdom' 'Argentina' 'Soviet Union\nRussia' 'Tunisia' 'Germany'
 'Thailand\nNepal\nIndia\nMalaysia' 'Yemen' 'Japan' 'Spain' 'Australia'
 'Mexico' 'China' 'Austria\nUnited States\nCzechoslovakia' 'Canada'
 'France' 'Turkey' 'Indonesia' 'Bangladesh' 'Belgium' 'Ukraine' 'India'
 'Soviet Union\nRussia\nUkraine'
 'East Germany\nGermany\nFrance\nSpain\nCzech Republic (suspected)\nItaly (suspected)'
 'German Empire\nGermany' 'Denmark' 'China\nJapan'
 'Spain\nFrance (claimed)\nItaly (claimed)' 'Canada\nUnited States'
 'Colombia' 'Cyprus' 'Belarus' 'Costa Rica'
 'United States\n Portuguese Angola'
 'Switzerland\nFrance\nUnited States\nYugoslavia (suspected)\nItaly (suspected)'
 'Czechoslovakia' 'Singapore' 'Swaziland' 'Greece' 'Austria-Hungary'
 'Iran' 'France\nGermany (suspected)\nSwitzerland (suspected)' 'Ecuador'
 'United States\nCanada' 'Soviet Union\nRussia\nTajikistan' 'Romania'
 'Afghanistan' 'Peru' 'France\nBelgium' 'Venezuela'
 'United States\nMexico' 'Colombia\nEcuador\nVenezuela'
 'Colombia\nPeru\nEcuador' 'Colombia\nEcuador\nBrazil (alleged)'
 'Soviet Union\nUkraine' 'Morocco'
 'Kingdom of Romania\nYugoslavia\nHungary (alleged)'
 'Ottoman Empire\n Iraq\n Iran' 'Egypt' 'Austria'
 'Allied-occupied Germany\nWest Germany' 'Netherlands']

In [15]:
# Розділяємо рядок, якщо є декілька країн. Прибираємо пробіли та такі слова як: (alleged), (suspected).
sk["Country"] = sk["Country"].str.replace(r'\n', ',', regex = True)

sk_long = sk.assign(
    Country = sk['Country'].str.split(r',\s*')
).explode('Country').reset_index(drop=True)

sk_long['Country'] = sk_long['Country'].str.strip()

sk_long["Country"] = sk_long["Country"].str.replace(r"\(.*?\)", "", regex=True)

print(sk_long['Country'].unique())

['United States' 'Soviet Union' 'Poland' 'Italy' 'West Germany' 'Brazil'
 'Chile' 'Russia' 'South Korea' 'Pakistan' 'Latvia' 'South Africa'
 'United Kingdom' 'Argentina' 'Tunisia' 'Germany' 'Thailand' 'Nepal'
 'India' 'Malaysia' 'Yemen' 'Japan' 'Spain' 'Australia' 'Mexico' 'China'
 'Austria' 'Czechoslovakia' 'Canada' 'France' 'Turkey' 'Indonesia'
 'Bangladesh' 'Belgium' 'Ukraine' 'East Germany' 'Czech Republic '
 'Italy ' 'German Empire' 'Denmark' 'France ' 'Colombia' 'Cyprus'
 'Belarus' 'Costa Rica' 'Portuguese Angola' 'Switzerland' 'Yugoslavia '
 'Singapore' 'Swaziland' 'Greece' 'Austria-Hungary' 'Iran' 'Germany '
 'Switzerland ' 'Ecuador' 'Tajikistan' 'Romania' 'Afghanistan' 'Peru'
 'Venezuela' 'Brazil ' 'Morocco' 'Kingdom of Romania' 'Yugoslavia'
 'Hungary ' 'Ottoman Empire' 'Iraq' 'Egypt' 'Allied-occupied Germany'
 'Netherlands']

In [16]:
# Перейменовуємо старі назви країн на сучасні за допомогою словника відповідностей
replace_dict = {
    'Soviet Union': 'Russia',
    'West Germany': 'Germany',
    'East Germany': 'Germany',
    'Czechoslovakia': 'Czechia',
    'German Empire': 'Germany',
    'Austria-Hungary': 'Austria',
    'Ottoman Empire': 'Turkey',
    'Kingdom of Romania': 'Romania',
    'Allied-occupied Germany': 'Germany',
    'Portuguese Angola': 'Angola',
    'Yugoslavia': 'Serbia',
    'Swaziland': 'Eswatini'
}

sk_long["Country"] = sk_long["Country"].replace(replace_dict)

print(sk_long["Country"].unique())

['United States' 'Russia' 'Poland' 'Italy' 'Germany' 'Brazil' 'Chile'
 'South Korea' 'Pakistan' 'Latvia' 'South Africa' 'United Kingdom'
 'Argentina' 'Tunisia' 'Thailand' 'Nepal' 'India' 'Malaysia' 'Yemen'
 'Japan' 'Spain' 'Australia' 'Mexico' 'China' 'Austria' 'Czechia' 'Canada'
 'France' 'Turkey' 'Indonesia' 'Bangladesh' 'Belgium' 'Ukraine'
 'Czech Republic ' 'Italy ' 'Denmark' 'France ' 'Colombia' 'Cyprus'
 'Belarus' 'Costa Rica' 'Angola' 'Switzerland' 'Yugoslavia ' 'Singapore'
 'Eswatini' 'Greece' 'Iran' 'Germany ' 'Switzerland ' 'Ecuador'
 'Tajikistan' 'Romania' 'Afghanistan' 'Peru' 'Venezuela' 'Brazil '
 'Morocco' 'Serbia' 'Hungary ' 'Iraq' 'Egypt' 'Netherlands']

In [17]:
sk_long["Possible victims"] = sk_long["Possible victims"].str.replace("+", "")
print(sk_long["Possible victims"])

0         80
1         29
2         21
3         16
4        NaN
       ...
346        -
347        4
348    9-100
349        8
350        3
Name: Possible victims, Length: 351, dtype: object

In [18]:
import pandas as pd
import re

def process_victims(value):
    if pd.isna(value) or str(value).strip() == '':
        return pd.NA

    # Видаляємо коми (на випадок 1,000-2,000)
    cleaned = str(value).replace(',', '')

    # Знаходимо всі послідовності цифр
    numbers = re.findall(r'\d+', cleaned)

    if len(numbers) == 2:
        low = int(numbers[0])
        high = int(numbers[1])
        return (low + high) / 2.0          # середнє (може бути float)
    elif len(numbers) == 1:
        return int(numbers[0])
    else:
        return pd.NA                          # нічого не знайшли

# Застосовуємо до твоєї колонки
sk_long['Possible victims'] = sk_long['Possible victims'].apply(process_victims)

# Перетворюємо всю колонку на числовий тип (дуже зручно для аналізу)
sk_long['Possible victims'] = pd.to_numeric(sk_long['Possible victims'], errors='coerce')

# Перевіряємо результат
print(sk_long['Possible victims'])

0      80.0
1      29.0
2      21.0
3      16.0
4       NaN
       ...
346     NaN
347     4.0
348    54.5
349     8.0
350     3.0
Name: Possible victims, Length: 351, dtype: float64

In [23]:
# Так як в колонці "Possible victims" діапазон можливих жертв, беремо середнє арифметичне, щоб приблизно вирахувати кількість недоведених вбивств
import re

def parse_victims(val):
    if pd.isna(val):
        return None

    val = str(val).strip()

    # Якщо діапазон типу "9-100" або "9–100"
    match = re.match(r'(\d+)\s*[-–]\s*(\d+)', val)
    if match:
        low, high = int(match.group(1)), int(match.group(2))
        return round((low + high) / 1)

    # Якщо просто число
    match = re.match(r'(\d+)', val)
    if match:
        return int(match.group(1))

    return None

sk_long['victims_count'] = sk_long['Possible victims'].apply(parse_victims).astype('Int64')
print(sk_long.head(20))

                        Name         Country    Years active Proven victims  \
0          Carl Eugene Watts   United States    1974 to 1982             14
1             Philipp Tyurin          Russia    1945 to 1946             14
2        Zdzisław Marchwicki          Poland    1964 to 1970             14
3        Monster of Florence           Italy    1968 to 1985             14
4              Joachim Kroll         Germany    1955 to 1976             14
5           Arthur Shawcross   United States    1972 to 1989             14
6                The Doodler   United States    1974 to 1975             14
7   Marcelo Costa de Andrade          Brazil            1991             14
8          Julio Pérez Silva           Chile    1998 to 2001             14
9            Sergey Shipilov          Russia    1995 to 1999             14
10         Abdufatto Zamanov          Russia    2002 to 2004             14
11             Jeong Nam-gyu     South Korea    2004 to 2006             14
12               Amir Qayyum        Pakistan            2005             14
13                 Jake Bird   United States   1930s to 1947             13
14             Belle Gunness   United States  1900? to 1908?             13
15  Cleveland Torso Murderer   United States    1934 to 1938             13
16           Kaspars Petrovs          Latvia            2003             13
17           Richard Ramirez   United States    1984 to 1985             13
18      Sleepy Hollow Killer    South Africa   1990s to 2007             13
19           Peter Sutcliffe  United Kingdom    1975 to 1980             13

    Possible victims                                              Notes  \
0               80.0  Believed to have killed over 80 women in multi...
1               29.0  Known as the "Leningrad Maniac" and the "Hellr...
2               21.0  Also known as Vampire of Zagłębie. Killed 14 w...
3               16.0  Unidentified killer who shot couples in lovers...
4                NaN  Known as the "Ruhr Cannibal" and "The Duisburg...
5                NaN  Committed arson and burglary, served two years...
6                NaN  Unidentified serial killer who sketched then s...
7                NaN  Known as The Vampire of Niterói. Raped and kil...
8                NaN  Known as The Psychopath from Alto Hospicio; ki...
9                NaN  Known as the "Velsk Chikatilo"; killed female ...
10               NaN  Killed people out of personal hostility; also ...
11               NaN  Kidnapped, raped and murdered people; committe...
12               NaN  Known as "The brick killer". Killed 14 homeles...
13              44.0  Sentenced to death for the murders of two peop...
14              40.0  Norwegian-born murder-for-profit killer who mu...
15              40.0  Unidentified serial killer, also known as "The...
16              38.0  Confessed to strangling 38 elderly residents o...
17              20.0  Killed 13 people between 28 June 1984, and 24 ...
18              16.0  Raped and murdered women, mostly sex workers, ...
19              15.0  Killed 13 women between 30 October 1975, and 1...

    birth_date  birth_day  birth_month  birth_year       zodiac  victims_count
0   1953-11-07          7           11        1953      Scorpio             80
1   1970-01-01       <NA>         <NA>        1910         None             29
2   1927-10-18         18           10        1927        Libra             21
3          NaT       <NA>         <NA>        <NA>         None             16
4   1933-04-17         17            4        1933        Aries           <NA>
5   1945-06-06          6            6        1945       Gemini           <NA>
6          NaT       <NA>         <NA>        <NA>         None           <NA>
7   1967-01-02          2            1        1967    Capricorn           <NA>
8   1963-07-15         15            7        1963       Cancer           <NA>
9   1959-05-17         17            5        1959       Taurus           <NA>
10  1973-04-07          7            4        2026        Aries           <NA>
11  1969-04-17         17            4        1969        Aries           <NA>
12  1970-01-01       <NA>         <NA>        1981         None           <NA>
13  1901-12-14         14           12        1901  Sagittarius             44
14         NaT         11           11        1859      Scorpio             40
15         NaT       <NA>         <NA>        <NA>         None             40
16  1970-01-01       <NA>         <NA>        1978         None             38
17  1960-02-29         29            2        1960       Pisces             20
18         NaT       <NA>         <NA>        <NA>         None             16
19  1946-06-02          2            6        1946       Gemini             15

In [33]:
# Визначимо різницю між можливими жертвами та доведеними
sk_long['Proven victims'] = pd.to_numeric(sk['Proven victims'], errors='coerce').astype('Int64')
sk_long['victims_gap'] = sk_long['victims_count'] - sk_long['Proven victims']
print(sk_long['victims_gap'].head())

0      66
1      15
2       7
3       2
4    <NA>
Name: victims_gap, dtype: Int64

In [35]:
# Визначимо роки активності серійних маніяків
sk_long['years_active_count'] = sk_long['Years active'].str.extract(r'(\d{4}).*(\d{4})').apply(
    lambda x: int(x[1]) - int(x[0]) if pd.notna(x[1]) else 0, axis=1
)
print(sk_long['years_active_count'].head(20))

0      8
1      1
2      6
3     17
4     21
5     17
6      1
7      0
8      3
9      4
10     2
11     2
12     0
13    17
14     8
15     4
16     0
17     1
18    17
19     5
Name: years_active_count, dtype: int64

In [39]:
# Розподілимо дати народження на декади
sk_long['birth_decade'] = (sk['birth_year'] // 10) * 10
print(sk_long['birth_decade'].head())

0    1950
1    1910
2    1920
3    <NA>
4    1930
Name: birth_decade, dtype: Int64